### PR TITLE
Refactoring for improvements

### PR DESCRIPTION
**Pull request by gabin-dongmo**
- Renamed CountryData to UserProfile
- Extracted SvgViewBox component
- Provided strong type for props in Card and PreviewCard
- Improved typing
- Extracted CardSocial component to improve readability

### CODE REVIEW

**Comment by ln-dev7** [comment]
Why change CountryData to UserProfile ?

also, this amendment would update the https://github.com/ln-dev7/world-portfolios/issues/80

**Comment by gabin-dongmo** [comment]
> Why change CountryData to UserProfile ?
> 
> also, this amendment would update the #80

Because the interface refers conceptually to a user's profile instead of a country. Granted, we have profiles organized by countries, but they're still user profiles.

**Comment by ln-dev7** [comment]
Okay, I understand better, thank

@Sanix-Darker , could you give your opinion please?

**Comment by gabin-dongmo** [comment]
I realize I went ahead of myself and pushed changes without specifying the issues addressed. I will close this PR and introduce a proper issue to illustrate the changes suggested.
@ln-dev7

**Pull request closed without merging**
